### ISSUE TITLE
How to handle corner case in GEMM

### ISSUE THREAD

**Issue by wudu98** [AnonymousYWL/LibShalom#3]
Hello! 
I'm learning from your work in this project. 
I have a question about how to handle the corner case in GEMM. 
From your code I am not sure weather you solve N is not divisible by 16 and K is not divisible by 4.

**Comment by AnonymousYWL** [comment]
Hello! Thank you for your interest in this work.
The code here is incomplete! I will release more complete code later.
Sorry, this work is preparing other journals.

**Comment by wudu98** [comment]
Ths. It's a job worth learning.
